// Generated by CoffeeScript 1.3.3
var Bookmark, americano;

americano = require('americano-cozy');

module.exports = Bookmark = americano.getModel('Bookmark', {
  'title': {
    type: String
  },
  'url': {
    type: String
  },
  'tags': {
    type: String
  },
  'description': {
    type: String
  },
  'created': {
    type: Date,
    "default": Date
  }
});

Bookmark.all = function(params, callback) {
  return Bookmark.request("all", params, callback);
};
