// Generated by CoffeeScript 1.3.3
var americano;

americano = require('americano-cozy');

module.exports = {
  bookmark: {
    all: function(doc) {
      return emit(Date.parse(doc.created), doc);
    }
  }
};
