// Generated by CoffeeScript 1.7.1
var Bookmark;

Bookmark = require('../models/bookmark');

module.exports.all = function(req, res) {
  return Bookmark.all(function(err, bookmarks) {
    var msg;
    if (err) {
      console.log(err);
      msg = "Server error occured while retrieving data.";
      return res.send({
        error: true,
        msg: msg
      });
    } else {
      return res.send(bookmarks);
    }
  });
};

module.exports.create = function(req, res) {
  return Bookmark.create(req.body, (function(_this) {
    return function(err, bookmark) {
      var msg;
      if (err) {
        console.log(err);
        msg = "Server error while creating bookmark.";
        return res.send({
          error: true,
          msg: msg
        }, 500);
      } else {
        return res.send(bookmark);
      }
    };
  })(this));
};

module.exports.destroy = function(req, res) {
  return Bookmark.find(req.params.id, (function(_this) {
    return function(err, bookmark) {
      if ((err != null) || (bookmark == null)) {
        return res.send({
          error: true,
          msg: "Bookmark not found"
        }, 404);
      } else {
        return bookmark.destroy(function(err) {
          if (err) {
            console.log(err);
            res.send({
              error: 'Cannot destroy bookmark'
            }, 500);
          } else {
            res.send({
              success: 'Bookmark succesfuly deleted'
            });
          }
          return bookmark = null;
        });
      }
    };
  })(this));
};
