// Generated by CoffeeScript 1.3.3
var bookmarks;

bookmarks = require('./bookmarks');

module.exports = {
  'bookmarks': {
    get: bookmarks.all,
    post: bookmarks.create
  },
  'bookmarks/:id': {
    "delete": bookmarks.destroy
  }
};
